#!/bin/bash
initial="$(pwd)"
separator="$DEV_PATH/www"
pathAfterSeparator="${initial//$separator/}"

C=''
for i in "$@"; do 
    i="${i//\\/\\\\}"
    C="$C \"${i//\"/\\\"}\""
done

docker exec -ti -w /var/www$pathAfterSeparator php7 su -s /bin/bash -c "php $C" www-data